name: Update AUI Version

on:
  push:
    tags-ignore:
      - v*rc*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GIT_SUBMODULE_STRATEGY: recursive

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update Tag
        shell: bash
        run: |
          git config user.name noreply
          git config user.email "noreply@github.com"
          TAG=${GITHUB_REF##*/}
          echo "New tag: $TAG"
          git fetch origin master
          git checkout master
          sed -i "s/set(AUI_VERSION.*)/set\(AUI_VERSION $TAG\)/g" README.md
          git add README.md
          git commit -m "update AUI version"
          git push

  update-examples:
    name: Update ${{ matrix.url }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        url: ["https://github.com/aui-framework/example_app"]
    steps:
      - name: Update Tag
        shell: bash
        run: |
          git clone ${{ matrix.url }} repo
          cd repo
          git config user.name noreply
          git config user.email "noreply@github.com"
          TAG=${GITHUB_REF##*/}
          echo "New tag: $TAG"
          git checkout -b feat/update-aui-$TAG
          sed -i "s/set(AUI_VERSION.*)/set\(AUI_VERSION $TAG\)/g" CMakeLists.txt
          git add -A
          git commit -m "update AUI version"
          gh pr create --title "Update to $TAG"

